//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basket()
        {
            this.BasketItems = new HashSet<BasketItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string EmailAddress { get; set; }
        public string IPAddress { get; set; }
        public string SessionId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int Status { get; set; }
        public string Message { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Companyname { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> HeardAboutUs { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> KeepInTouch { get; set; }
        public Nullable<int> FriendTitleId { get; set; }
        public string FriendForename { get; set; }
        public string FriendSurname { get; set; }
        public string FriendEmailAddress { get; set; }
        public string FriendContactNumber { get; set; }
        public Nullable<bool> EmailToFriend { get; set; }
    
        public virtual ApplicantTitle ApplicantTitle { get; set; }
        public virtual ApplicantTitle ApplicantTitle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketItem> BasketItems { get; set; }
    }
}
