//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportConfig
    {
        public int ID { get; set; }
        public Nullable<int> ExportMediaID { get; set; }
        public string PropertyCategoryList { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public Nullable<decimal> MaximumPrice { get; set; }
        public Nullable<int> MinimumBedrooms { get; set; }
        public Nullable<int> MaximumBedrooms { get; set; }
        public string PropertyClientTypeList { get; set; }
        public string PropertyTypeList { get; set; }
        public string SearchTypeList { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime LastUploadDate { get; set; }
        public bool Active { get; set; }
        public bool DisplayCategoryTypes { get; set; }
        public bool DisplayClientTypes { get; set; }
        public bool DisplayPropertyTypes { get; set; }
        public bool DisplayMinBedrooms { get; set; }
        public bool DisplayMaxBedrooms { get; set; }
        public bool AllowMultipleCategoryTypes { get; set; }
        public Nullable<int> RightMoveChannel { get; set; }
        public string RightMoveAgentRef { get; set; }
    
        public virtual ExportMedia ExportMedia { get; set; }
    }
}
