//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.PropertyEstates = new HashSet<PropertyEstate>();
            this.PropertySurveys = new HashSet<PropertySurvey>();
        }
    
        public int id { get; set; }
        public int branchid { get; set; }
        public string officename { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string towncity { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string telephone { get; set; }
        public string telephoneLet { get; set; }
        public string fax { get; set; }
        public string image { get; set; }
        public string emailaddress { get; set; }
        public string salesemailaddress { get; set; }
        public Nullable<int> priority { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyEstate> PropertyEstates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertySurvey> PropertySurveys { get; set; }
    }
}
