//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyFileType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyFileType()
        {
            this.PropertyFiles = new HashSet<PropertyFile>();
        }
    
        public int id { get; set; }
        public int vebraid { get; set; }
        public string filetype { get; set; }
        public bool download { get; set; }
        public string ExpertAgentFileType { get; set; }
        public Nullable<int> ExpertAgentID { get; set; }
        public Nullable<int> RightMoveID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFile> PropertyFiles { get; set; }
    }
}
