//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertySurvey
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public string BesttimeToCall { get; set; }
        public string AlternativeTelephone { get; set; }
        public string BesttimeToCall1 { get; set; }
        public string Mobilenumber { get; set; }
        public int PropertyTypeID { get; set; }
        public string PropertyAge { get; set; }
        public Nullable<decimal> PropertyPrice { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string County { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> Valuation { get; set; }
        public Nullable<bool> Survey { get; set; }
        public Nullable<bool> EPC { get; set; }
        public int OfficeId { get; set; }
    
        public virtual Office Office { get; set; }
        public virtual PropertyType PropertyType { get; set; }
    }
}
