//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImportProcess
    {
        public int id { get; set; }
        public int ImportSourse { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsRunning { get; set; }
        public bool IsManualProcess { get; set; }
        public string Notes { get; set; }
    
        public virtual ImportType ImportType { get; set; }
    }
}
