//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAlert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyAlert()
        {
            this.PropertyAlertsProcesseds = new HashSet<PropertyAlertsProcessed>();
        }
    
        public int ID { get; set; }
        public int Title { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public string PropertyTypeIDs { get; set; }
        public string PropertyTypeTitles { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public Nullable<double> MaxPrice { get; set; }
        public Nullable<int> MinBedrooms { get; set; }
        public Nullable<int> MaxBedrooms { get; set; }
        public string Location { get; set; }
        public Nullable<double> Radius { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.DateTime SubscriptionStartDate { get; set; }
        public System.DateTime SubscriptionExpiryDate { get; set; }
        public System.Guid SubscriptionCode { get; set; }
        public Nullable<System.DateTime> DateProcessed { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> PPPW { get; set; }
        public Nullable<bool> PCM { get; set; }
        public Nullable<bool> Portfolios { get; set; }
        public bool Terms { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ClientType { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsAlert { get; set; }
        public string AddedBy { get; set; }
    
        public virtual ApplicantTitle ApplicantTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyAlertsProcessed> PropertyAlertsProcesseds { get; set; }
    }
}
