//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyTypeGroup
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool Active { get; set; }
        public int Priority { get; set; }
        public bool IsSale { get; set; }
        public bool IsLet { get; set; }
        public bool IsNewHomes { get; set; }
        public bool IsInvestment { get; set; }
        public bool SubType { get; set; }
    }
}
