//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyRoom
    {
        public int id { get; set; }
        public int propertyid { get; set; }
        public Nullable<int> priority { get; set; }
        public string title { get; set; }
        public string imperial { get; set; }
        public string metric { get; set; }
        public string description { get; set; }
        public string dimensions { get; set; }
        public Nullable<int> fileindex { get; set; }
        public bool isImported { get; set; }
        public Nullable<int> importedsource { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual PropertyEstate PropertyEstate { get; set; }
    }
}
