//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAlertsProcessed
    {
        public int Id { get; set; }
        public int PropertyAlertID { get; set; }
        public Nullable<System.DateTime> DateAlertSent { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<double> priceend { get; set; }
        public Nullable<double> pricePCM { get; set; }
    
        public virtual PropertyAlert PropertyAlert { get; set; }
    }
}
