//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public int imageid { get; set; }
        public int propertyid { get; set; }
        public string room { get; set; }
        public string image { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
