//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyFile
    {
        public int id { get; set; }
        public int propertyid { get; set; }
        public string filename { get; set; }
        public string originalfilename { get; set; }
        public int FileType { get; set; }
        public Nullable<int> priority { get; set; }
        public string caption { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string VebraURL { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> IsImported { get; set; }
        public Nullable<int> importedsource { get; set; }
        public Nullable<bool> FileExistOnFeed { get; set; }
    
        public virtual PropertyEstate PropertyEstate { get; set; }
        public virtual PropertyFileType PropertyFileType { get; set; }
    }
}
