//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyStatu()
        {
            this.PropertyEstates = new HashSet<PropertyEstate>();
        }
    
        public int propertystatusid { get; set; }
        public string title { get; set; }
        public int priority { get; set; }
        public int catid { get; set; }
        public int vebraid { get; set; }
        public Nullable<int> ExpertAgentID { get; set; }
        public Nullable<bool> Tag { get; set; }
        public Nullable<int> RightmoveStatus { get; set; }
        public Nullable<int> ZooplaStatus { get; set; }
    
        public virtual PropertyCategory PropertyCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyEstate> PropertyEstates { get; set; }
    }
}
