//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyEstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropertyEstate()
        {
            this.BasketItems = new HashSet<BasketItem>();
            this.ExportMediaLogs = new HashSet<ExportMediaLog>();
            this.PropertyEstateClientTypes = new HashSet<PropertyEstateClientType>();
            this.PropertyEstateTypes = new HashSet<PropertyEstateType>();
            this.PropertyFiles = new HashSet<PropertyFile>();
            this.PropertyOptions = new HashSet<PropertyOption>();
            this.PropertyRooms = new HashSet<PropertyRoom>();
            this.WindowCards = new HashSet<WindowCard>();
        }
    
        public int id { get; set; }
        public Nullable<int> vebraid { get; set; }
        public Nullable<int> importedsource { get; set; }
        public string ExpertAgentRef { get; set; }
        public string agentref { get; set; }
        public Nullable<int> developmentid { get; set; }
        public Nullable<int> propertytypeid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> clienttypeid { get; set; }
        public string housename { get; set; }
        public string housenumber { get; set; }
        public string fulladdress { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string towncity { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string postcode1 { get; set; }
        public string postcode2 { get; set; }
        public Nullable<byte> regionid { get; set; }
        public bool coastal { get; set; }
        public bool equestrian { get; set; }
        public string mainimage { get; set; }
        public string shortdescription { get; set; }
        public string longdescription { get; set; }
        public string roominformation { get; set; }
        public string footer { get; set; }
        public decimal pricestart { get; set; }
        public Nullable<decimal> priceend { get; set; }
        public Nullable<decimal> pricePCM { get; set; }
        public string pricetext { get; set; }
        public bool offersInExcess { get; set; }
        public int bedrooms { get; set; }
        public int receptions { get; set; }
        public int bathrooms { get; set; }
        public bool active { get; set; }
        public int officeid { get; set; }
        public Nullable<int> propertystatusid { get; set; }
        public Nullable<System.DateTime> propertydate { get; set; }
        public System.DateTime dateadded { get; set; }
        public Nullable<bool> israre { get; set; }
        public string energydocument { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitudeInDegrees { get; set; }
        public Nullable<double> longitudeInDegrees { get; set; }
        public Nullable<int> onlineenquiries { get; set; }
        public Nullable<System.DateTime> lastvieweddate { get; set; }
        public string video { get; set; }
        public string videodescription { get; set; }
        public string floorplan { get; set; }
        public Nullable<bool> HasImage { get; set; }
        public Nullable<bool> Tour { get; set; }
        public int Furnished { get; set; }
        public string locality { get; set; }
        public bool priceispcm { get; set; }
        public bool displayprice { get; set; }
        public string displayaddress { get; set; }
        public string vebra360 { get; set; }
        public bool IsImported { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<decimal> LetDeposit { get; set; }
        public Nullable<decimal> LetAgencyFee { get; set; }
        public Nullable<bool> FixedDeposit { get; set; }
        public Nullable<int> EPCEnergyCurrent { get; set; }
        public Nullable<int> EPCEnergyPotential { get; set; }
        public Nullable<int> EPCCo2Current { get; set; }
        public Nullable<int> EPCCo2Potential { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> DoNotExport { get; set; }
        public Nullable<bool> DoNotImportData { get; set; }
        public Nullable<System.DateTime> PropertyEndDate { get; set; }
        public Nullable<bool> Portfolio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketItem> BasketItems { get; set; }
        public virtual DevelopmentGroup DevelopmentGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExportMediaLog> ExportMediaLogs { get; set; }
        public virtual FurnishedType FurnishedType { get; set; }
        public virtual ImportType ImportType { get; set; }
        public virtual Office Office { get; set; }
        public virtual PropertyCategory PropertyCategory { get; set; }
        public virtual PropertyClientType PropertyClientType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyEstateClientType> PropertyEstateClientTypes { get; set; }
        public virtual PropertyStatu PropertyStatu { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Region Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyEstateType> PropertyEstateTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFile> PropertyFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyOption> PropertyOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRoom> PropertyRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WindowCard> WindowCards { get; set; }
    }
}
