//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyOption
    {
        public int id { get; set; }
        public int propertyid { get; set; }
        public string Options { get; set; }
        public string MetricSize { get; set; }
        public int Optiontype { get; set; }
        public bool IsImported { get; set; }
        public Nullable<int> importedsource { get; set; }
        public Nullable<int> FieldId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual PropertyEstate PropertyEstate { get; set; }
    }
}
