//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public long trackingid { get; set; }
        public byte trackingtypeid { get; set; }
        public int propertyid { get; set; }
        public Nullable<int> vipid { get; set; }
        public System.DateTime trackingdate { get; set; }
    
        public virtual TrackingType TrackingType { get; set; }
    }
}
