//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowCard
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string FooterText { get; set; }
        public string URL { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public string Template { get; set; }
        public string BackGroundImage { get; set; }
        public string PropertyImage { get; set; }
        public string ShortlistKey { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual PropertyEstate PropertyEstate { get; set; }
    }
}
